const SITE = {
  title: "THE FOCUX",
  description: "Nootropicos, ciencia de peptidos y rendimiento humano sin hype.",
};

const css = `
:root{color-scheme:dark;--bg:#060606;--ink:#f4ead4;--muted:#b9a987;--gold:#d7a744;--line:rgba(215,167,68,.28);--panel:rgba(15,15,13,.76)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#060606;color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;line-height:1.5}
a{color:inherit}.site-header{position:fixed;z-index:20;inset:0 0 auto;display:flex;align-items:center;justify-content:space-between;padding:18px clamp(18px,4vw,56px);background:linear-gradient(180deg,rgba(0,0,0,.82),rgba(0,0,0,.2));border-bottom:1px solid rgba(215,167,68,.16);backdrop-filter:blur(16px)}
.wordmark{display:flex;gap:12px;align-items:center;text-decoration:none;font-family:Georgia,serif;letter-spacing:.14em}.mark{width:34px;height:34px;border:1px solid var(--gold);border-radius:50%;display:grid;place-items:center;box-shadow:0 0 30px rgba(215,167,68,.32)}.mark:before{content:"";width:18px;height:18px;border:2px solid var(--gold);border-left-color:transparent;border-radius:50%}
nav{display:flex;gap:26px;color:#dacda9;font-size:12px;letter-spacing:.08em;text-transform:uppercase}nav a{text-decoration:none}.button{border:1px solid var(--gold);background:linear-gradient(135deg,#f1cf7c,#a9781f);color:#130d03;text-decoration:none;padding:13px 20px;border-radius:3px;font-weight:800;text-transform:uppercase;letter-spacing:.08em;font-size:12px;cursor:pointer}.button.ghost{background:transparent;color:var(--gold)}
.hero{min-height:96vh;position:relative;display:grid;align-items:end;overflow:hidden;padding:120px clamp(22px,6vw,80px) 48px}.hero:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 72% 20%,rgba(215,167,68,.25),transparent 28%),radial-gradient(circle at 30% 45%,rgba(73,145,165,.2),transparent 34%),linear-gradient(90deg,#070707 0%,rgba(7,7,7,.78) 45%,rgba(7,7,7,.35) 100%);z-index:0}.hero:after{content:"";position:absolute;right:-8vw;bottom:4vh;width:min(760px,78vw);height:min(760px,78vw);border-radius:50%;border:1px solid rgba(215,167,68,.38);box-shadow:inset 0 0 90px rgba(215,167,68,.1),0 0 80px rgba(215,167,68,.16);background:repeating-radial-gradient(circle,rgba(215,167,68,.2) 0 1px,transparent 1px 18px);opacity:.9}
.city{position:absolute;right:3vw;bottom:12vh;width:min(720px,70vw);height:360px;z-index:1;opacity:.82}.tower{position:absolute;bottom:0;width:8%;background:linear-gradient(180deg,rgba(215,167,68,.85),rgba(22,19,12,.85));border:1px solid rgba(215,167,68,.24);box-shadow:0 0 34px rgba(215,167,68,.2)}.tower:nth-child(1){left:3%;height:42%}.tower:nth-child(2){left:16%;height:70%}.tower:nth-child(3){left:30%;height:52%}.tower:nth-child(4){left:45%;height:86%}.tower:nth-child(5){left:62%;height:60%}.tower:nth-child(6){left:76%;height:78%}.tower:nth-child(7){left:90%;height:46%}
.hero-content{position:relative;z-index:2;max-width:760px}.eyebrow{color:var(--gold);text-transform:uppercase;letter-spacing:.28em;font-size:12px;font-weight:800}.hero h1{font-family:Georgia,serif;font-size:clamp(64px,13vw,154px);line-height:.86;margin:18px 0 20px;letter-spacing:.03em}.hero-copy{font-size:clamp(20px,2.8vw,34px);max-width:720px;color:#f2ead8}.hero-actions{display:flex;gap:14px;flex-wrap:wrap;margin:32px 0}.proof-line{display:flex;gap:18px;flex-wrap:wrap;color:#d8cba9;font-size:13px;text-transform:uppercase;letter-spacing:.06em}.proof-line span{border-left:1px solid var(--gold);padding-left:12px}
.section{padding:78px clamp(22px,6vw,80px);border-top:1px solid rgba(215,167,68,.16)}.grid{display:grid;grid-template-columns:1fr 1.3fr;gap:48px}.section h2{font-family:Georgia,serif;font-size:clamp(36px,6vw,78px);line-height:1;margin:8px 0 0}.lead{font-size:22px;color:#fff2cf}.muted{color:var(--muted)}
.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{background:var(--panel);border:1px solid var(--line);padding:26px;min-height:260px}.card span,.edition span{color:var(--gold);font-weight:900}.card h3,.edition h3{font-size:24px;margin:18px 0 10px}.card p,.edition p{color:#cfc1a0}
.band{min-height:520px;display:grid;align-items:end;background:radial-gradient(circle at 50% 32%,rgba(215,167,68,.2),transparent 30%),linear-gradient(135deg,#080808,#10100c 50%,#050505);position:relative;overflow:hidden}.band:before{content:"NEUROCITY";position:absolute;inset:auto 0 20px;font-family:Georgia,serif;font-size:16vw;font-weight:900;color:rgba(215,167,68,.07);white-space:nowrap}.band .inner{position:relative;max-width:780px}
.editions{display:grid;gap:14px}.edition{display:flex;justify-content:space-between;gap:20px;padding:26px;border:1px solid var(--line);background:rgba(255,255,255,.03)}
.standards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.standard{border-top:1px solid var(--gold);padding-top:18px;color:#d7c8a6}
.access{display:grid;grid-template-columns:1fr 1fr;gap:36px;background:linear-gradient(135deg,#0d0b08,#050505)}form{border:1px solid var(--line);background:rgba(10,10,10,.82);padding:26px;display:grid;gap:14px}label{display:grid;gap:8px;color:#dacda9;font-size:13px;text-transform:uppercase;letter-spacing:.06em}input,select{width:100%;padding:14px 12px;background:#080808;border:1px solid rgba(215,167,68,.32);color:#fff;border-radius:2px}input[type=checkbox]{width:auto}.consent{display:flex;align-items:flex-start;text-transform:none;letter-spacing:0}.honeypot{display:none}.status{min-height:24px;color:#f5d282}.status.error{color:#ffb1a8}
footer{padding:36px clamp(22px,6vw,80px);display:flex;justify-content:space-between;gap:18px;color:#aa9a7a;border-top:1px solid var(--line)}footer strong{font-family:Georgia,serif;color:var(--ink);font-size:24px}.links{display:flex;gap:18px}
@media(max-width:840px){nav{display:none}.hero{min-height:92vh}.city{opacity:.34;right:-20vw}.grid,.access{grid-template-columns:1fr}.cards,.standards{grid-template-columns:1fr}.edition,footer{display:grid}.hero-copy{font-size:21px}}
`;

function html() {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${SITE.title} | Nootropicos, peptidos y rendimiento</title><meta name="description" content="${SITE.description}"><meta name="theme-color" content="#060606"><meta property="og:title" content="THE FOCUX"><meta property="og:description" content="${SITE.description}"><link rel="canonical" href="https://thefocux.com/"><style>${css}</style></head><body>
  <header class="site-header"><a class="wordmark" href="/"><span class="mark"></span><span>THE FOCUX</span></a><nav><a href="#research">Research</a><a href="#neurocity">NeuroCity</a><a href="#selection">Seleccion</a><a href="#method">Metodo</a></nav><a class="button" href="#access">Unirme</a></header>
  <main>
    <section class="hero"><div class="city">${Array.from({length:7},()=>"<i class='tower'></i>").join("")}</div><div class="hero-content"><p class="eyebrow">Soon - Research for Human Performance</p><h1>THE FOCUX</h1><p class="hero-copy">Nootropicos, ciencia de peptidos y sistemas de rendimiento explicados para personas con decisiones reales que tomar.</p><div class="hero-actions"><a class="button" href="#access">Entrar en la lista</a><a class="button ghost" href="#research">Ver linea editorial</a></div><div class="proof-line"><span>Evidencia antes que hype</span><span>Riesgo visible</span><span>Conflictos declarados</span></div></div></section>
    <section class="section grid" id="research"><div><p class="eyebrow">La publicacion</p><h2>Un filtro serio para un mercado ruidoso.</h2></div><div><p class="lead">No necesitas cien recomendaciones. Necesitas distinguir evidencia, mecanismo, marketing y riesgo.</p><p class="muted">THE FOCUX publicara dossiers, comparativas, entrevistas y mapas de evidencia para profesionales, fundadores, operadores y perfiles 35+ interesados en rendimiento sostenible.</p></div></section>
    <section class="section"><div class="cards"><article class="card"><span>01</span><h3>Nootropicos</h3><p>Ingredientes, dosis, calidad de evidencia, interacciones y diferencia entre promesa comercial y resultado plausible.</p></article><article class="card"><span>02</span><h3>Peptidos</h3><p>Mecanismos, ensayos, usos clinicos autorizados y riesgos. Cobertura educativa, no prescripcion ni venta de compuestos no autorizados.</p></article><article class="card"><span>03</span><h3>Performance</h3><p>Sueno, hidratacion, analiticas, tecnologia y decisiones que determinan si una intervencion tiene sentido.</p></article></div></section>
    <section class="section band" id="neurocity"><div class="inner"><p class="eyebrow">Original series - Soon</p><h2>NEUROCITY</h2><p class="lead">Atencion, memoria, estres, sueno y energia convertidos en historias que se recuerdan. Ciencia compleja sin lenguaje infantil ni soluciones magicas.</p><a class="button ghost" href="#access">Recibir episodio piloto</a></div></section>
    <section class="section grid" id="selection"><div><p class="eyebrow">THE FOCUX Selection - Soon</p><h2>Comprar menos. Elegir mejor.</h2></div><div><p class="lead">Una seleccion pequena de suplementos, libros, tests y herramientas legalmente comercializables.</p><p class="muted">Cada ficha mostrara por que entra, evidencia, dosis, fabricante, limitaciones y relacion comercial.</p></div></section>
    <section class="section"><p class="eyebrow">Primeras ediciones</p><div class="editions"><article class="edition"><div><span>Mapa de evidencia</span><h3>Creatina mas alla del musculo</h3><p>Que sabemos sobre cognicion, fatiga, poblaciones y dosis estudiadas.</p></div><span>En produccion</span></article><article class="edition"><div><span>Dossier</span><h3>Como leer una promesa sobre peptidos</h3><p>Del mecanismo teorico a la evidencia humana, la regulacion y las senales de riesgo.</p></div><span>En investigacion</span></article><article class="edition"><div><span>Comparativa</span><h3>La anatomia de un nootropico premium</h3><p>Materia prima, dosis, certificado, margen, claims y transparencia.</p></div><span>Proximamente</span></article></div></section>
    <section class="section" id="method"><p class="eyebrow">Metodo editorial</p><h2>La confianza no se declara. Se documenta.</h2><div class="standards"><p class="standard">Jerarquia de evidencia: mecanismo, preclinico, ensayo humano, revision y consenso.</p><p class="standard">Contexto y limites: poblacion, dosis, duracion, resultado y conflictos.</p><p class="standard">Riesgo visible: interacciones, contraindicaciones e incertidumbre.</p><p class="standard">Independencia comercial: afiliacion y muestras identificadas.</p></div></section>
    <section class="section access" id="access"><div><p class="eyebrow">Founding list</p><h2>Recibe el primer dossier.</h2><p class="lead">Una edicion semanal, alertas importantes y acceso anticipado a THE FOCUX Selection.</p><p class="muted">Sin spam ni promesas milagrosas.</p></div><form id="waitlistForm"><label>Nombre<input name="name" maxlength="80" placeholder="Tu nombre"></label><label>Email<input name="email" type="email" required maxlength="180" placeholder="tu@email.com"></label><label>Me interesa<select name="profile"><option value="nootropics">Nootropicos y cognicion</option><option value="peptides">Ciencia de peptidos</option><option value="performance">Sistemas de rendimiento</option><option value="selection">Seleccion y comparativas</option></select></label><label class="consent"><input name="consent" type="checkbox" required><span>Acepto recibir THE FOCUX y comunicaciones relacionadas.</span></label><input class="honeypot" name="company" tabindex="-1" autocomplete="off"><button class="button" type="submit">Unirme a la founding list</button><p class="status" id="status" role="status"></p></form></section>
  </main><footer><div><strong>THE FOCUX</strong><p>Research for Human Performance.</p></div><div class="links"><a href="/privacidad">Privacidad</a><a href="/terminos">Terminos</a><a href="mailto:hola@thefocux.com">hola@thefocux.com</a></div></footer>
  <script>const f=document.querySelector('#waitlistForm'),s=document.querySelector('#status');f.addEventListener('submit',async e=>{e.preventDefault();s.className='status';if(!f.reportValidity())return;const b=f.querySelector('button');const old=b.textContent;b.disabled=true;b.textContent='Enviando...';try{const r=await fetch('/api/waitlist',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(f)))});const j=await r.json();if(!r.ok)throw new Error(j.error||'No se pudo completar.');f.reset();s.textContent=j.alreadyRegistered?'Ya estabas en la lista.':'Acceso solicitado. Bienvenido a la lista privada.'}catch(err){s.className='status error';s.textContent=err.message}finally{b.disabled=false;b.textContent=old}})</script>
</body></html>`;
}

function legal(kind) {
  const privacy = kind === "privacidad";
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${privacy ? "Privacidad" : "Terminos"} | THE FOCUX</title><style>${css}</style></head><body><header class="site-header"><a class="wordmark" href="/"><span class="mark"></span><span>THE FOCUX</span></a></header><main class="section" style="padding-top:130px;max-width:900px"><p class="eyebrow">${privacy ? "Privacidad" : "Terminos"}</p><h2>${privacy ? "Politica de privacidad" : "Terminos de uso"}</h2><p class="lead">THE FOCUX es una publicacion educativa sobre rendimiento humano, nootropicos y ciencia de peptidos.</p><p class="muted">${privacy ? "Si te unes a la lista guardamos tu email, nombre opcional, interes declarado, fecha de consentimiento, pais aproximado y fuente para enviarte contenido relacionado. Puedes solicitar baja o eliminacion escribiendo a hola@thefocux.com." : "El contenido no sustituye consejo medico, diagnostico ni tratamiento. No vendemos ni promovemos compuestos no autorizados. Las decisiones de salud deben tomarse con profesionales cualificados."}</p><p class="muted">Ultima actualizacion: 25 de junio de 2026.</p></main></body></html>`;
}

function json(body, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", "x-content-type-options": "nosniff" } });
}

async function waitlist(request, env) {
  let input;
  try { input = await request.json(); } catch { return json({ error: "Solicitud no valida." }, 400); }
  if (input.company) return json({ ok: true });
  const email = String(input.email || "").trim().toLowerCase();
  const name = String(input.name || "").trim().slice(0, 80);
  const profile = String(input.profile || "professional").slice(0, 40);
  const consent = input.consent === "on" || input.consent === true;
  if (!/^\S+@\S+\.\S+$/.test(email) || email.length > 180) return json({ error: "Introduce un email valido." }, 400);
  if (!consent) return json({ error: "Necesitamos tu consentimiento para incluirte en la lista." }, 400);
  if (!env.DB) return json({ error: "La lista privada se esta configurando." }, 503);
  const existing = await env.DB.prepare("SELECT id FROM waitlist WHERE email = ?").bind(email).first();
  if (existing) return json({ ok: true, alreadyRegistered: true });
  const country = request.cf?.country || "";
  const source = new URL(request.url).hostname;
  await env.DB.prepare("INSERT INTO waitlist (email, name, profile, consent_at, country, source) VALUES (?, ?, ?, datetime('now'), ?, ?)").bind(email, name, profile, country, source).run();
  return json({ ok: true, alreadyRegistered: false }, 201);
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.hostname === "www.thefocux.com") return Response.redirect(`https://thefocux.com${url.pathname}${url.search}`, 301);
    if (url.pathname === "/api/waitlist" && request.method === "POST") return waitlist(request, env);
    if (url.pathname === "/api/waitlist") return json({ error: "Metodo no permitido." }, 405);
    if (url.pathname === "/robots.txt") return new Response("User-agent: *\\nAllow: /\\nSitemap: https://thefocux.com/sitemap.xml\\n", { headers: { "content-type": "text/plain; charset=utf-8" } });
    if (url.pathname === "/sitemap.xml") return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://thefocux.com/</loc></url></urlset>`, { headers: { "content-type": "application/xml; charset=utf-8" } });
    if (url.pathname === "/privacidad" || url.pathname === "/privacidad.html") return new Response(legal("privacidad"), { headers: { "content-type": "text/html; charset=utf-8" } });
    if (url.pathname === "/terminos" || url.pathname === "/terminos.html") return new Response(legal("terminos"), { headers: { "content-type": "text/html; charset=utf-8" } });
    return new Response(html(), { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "public, max-age=300" } });
  },
};
